version: "3.7"
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "money626/ffmpeg-node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      # - ./:/home/node/app
      - share-data:/share
    ports:
    - 8081:8081
    #expose:
    #  - "8081"
    command: npm start